version: '3'
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=HhUzNpNLEaBRNOX2h030jHieRabCBbuDl7rNXvCS
      - ZONE=thsiis.me
      - SUBDOMAIN=n
      - PROXIED=false
      - TZ=Pacific/Auckland
