version: "3"
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: always
    container_name: cloudflare-ddns
    env_file: .env
    environment:
      - "PROXIED=false"
      - "TZ=Pacific/Auckland"