version: "3"

services:
  whoami:
    image: "containous/whoami"
    container_name: "whoami"
    restart: "always"
    hostname: "whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.rule=Host(`whoami.n.thsiis.me`)"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=production"
      # authelia
      - "traefik.http.routers.whoami.middlewares=authelia"

networks:
  default:
    external:
      name: traefik_net