version: "3"
services:
  qinglong:
    container_name: qinglong
    restart: always
    image: whyour/qinglong:2.13.8
    volumes:
      - "./data:/ql/data"
    ports:
      - "5700:5700"
      - "5701:5701"
    environment:
      - "ENABLE_HANGUP=true"
      - "ENABLE_WEB_PANEL=true"
      - "TZ=Pacific/Auckland"
    hostname: "qinglong"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qinglong.entrypoints=websecure"
      - "traefik.http.routers.qinglong.rule=Host(`qinglong.thsiis.me`)"
      - "traefik.http.routers.qinglong.tls=true"
      - "traefik.http.routers.qinglong.tls.certresolver=production"
      # authelia
      - "traefik.http.routers.qinglong.middlewares=authelia"

networks:
  default:
    external:
      name: traefik_net
